@startuml
skinparam object {
    BackgroundColor White
    BorderColor #8B4513
    ArrowColor #A0522D
}

' Objetos
object "<u>:Gerente</u>" as gerente
object "<u>:TelaGerente</u>" as tela
object "<u>:ControladorVendas</u>" as controle
object "<u>:Pedido</u>" as pedido

' Links e mensagens
gerente -right-> tela : 1: solicitarConsultaVendas(filtro) >
tela -down-> controle : 1.1: consultarVendas(filtro) >

' Consulta iterativa dos pedidos registrados
controle -right-> pedido : 1.1.1 *[para cada pedido registrado]: reunirDadosVenda(filtro) >
pedido -left-> controle : 1.1.2 *[para cada pedido registrado]: dadosVenda >

controle -up-> tela : 1.2: retornarListaVendas(listaVendas) >
tela -left-> gerente : 1.3: exibirVendas(listaVendas) >

@enduml
